Adjust JamitLabs/App SwiftLint.stencil according to new best practices
JamitLabs/ProjLintTemplates pull request #4
Opened 2019-04-03 14:19 UTC by fredpi

2019-04-03 14:21 UTC, fredpi commented
Should be merged together with https://github.com/JamitLabs/NewProjectTemplate-iOS/pull/17...

2019-04-04 08:28 UTC, Jeehut requested changes
Same as NPT project feedback.

2019-04-04 08:28 UTC, Dschee commented on JamitLabs/App/SwiftLint.stencil
> +nesting:
See my comment on the NPT project.

2019-04-05 08:12 UTC, Jeehut approved these changes

2019-04-05 08:12 UTC, merged